# Generated by Django 4.0.1 on 2022-01-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default="'bikes','cycle','car','boat", max_length=15),
        ),
    ]
