# Generated by Django 4.0.1 on 2022-01-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0002_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
