# Generated by Django 4.0.1 on 2022-02-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0005_rentalbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
