# Generated by Django 4.0.1 on 2022-02-02 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0007_alter_rentalbooking_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='CustomerName',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rentalapp.customer'),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='return_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rentalapp.vehicle'),
        ),
    ]
