# Generated by Django 4.0.1 on 2022-02-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0010_alter_rentalbooking_customername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='CustomerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.customer'),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.vehicle'),
        ),
    ]
