# Generated by Django 4.0.1 on 2022-02-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0011_alter_rentalbooking_customername_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalBooking',
        ),
    ]
