# Generated by Django 4.0.1 on 2022-02-02 04:12

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0013_rentalbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='rental_date',
            field=models.DateField(verbose_name=django.forms.widgets.DateInput),
        ),
    ]
