# Generated by Django 4.0.1 on 2022-02-02 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0014_alter_rentalbooking_rental_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='CustomerName',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.customer'),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='rental_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.vehicle'),
        ),
    ]
