# Generated by Django 4.0.1 on 2022-02-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0015_alter_rentalbooking_customername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='rental_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
