# Generated by Django 4.0.1 on 2022-02-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0016_alter_rentalbooking_rental_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='return_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
