# Generated by Django 4.0.1 on 2022-02-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0019_rename_customername_rentalbooking_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='rental_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='return_date',
            field=models.DateTimeField(default=0),
        ),
    ]
