# Generated by Django 4.0.1 on 2022-02-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0020_alter_rentalbooking_rental_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='return_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
