# Generated by Django 4.0.1 on 2022-02-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0022_alter_rentalbooking_rental_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalBooking',
        ),
    ]
