# Generated by Django 4.0.1 on 2022-02-03 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0023_delete_rentalbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('Customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.customer')),
                ('vehicle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.vehicle')),
            ],
        ),
    ]
