# Generated by Django 4.0.1 on 2022-02-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0024_rentalbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='return_date',
            field=models.DateField(default=0, null=True),
        ),
    ]
