# Generated by Django 4.0.1 on 2022-02-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0025_alter_rentalbooking_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalbooking',
            old_name='Customer',
            new_name='CustomerName',
        ),
        migrations.RenameField(
            model_name='rentalbooking',
            old_name='vehicle',
            new_name='vehicle_type',
        ),
    ]
