# Generated by Django 4.0.1 on 2022-02-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0026_rename_customer_rentalbooking_customername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
